language: c
compiler:
  - clang
  - gcc

script:
  # check that we can compile STEPWAT2
  - set CPPFLAGS=-DSWDEBUG && make clean && make
  # check that we can run the 'default' example
  - ./testing.sagebrush.master/Stepwat_Inputs/stepwat -d testing.sagebrush.master/Stepwat_Inputs/ -f files.in -s -o -i
  # remove created files including (possibly) large output
  - make cleanall
