platform:
  - x86
  - Any CPU

matrix:
  fast_finish: true

install:
  - git submodule update --init --recursive

# to run your custom scripts instead of automatic MSBuild
build_script:
  - set PATH=%PATH%;c:\cygwin\bin
  # check that we can compile STEPWAT2
  - set CPPFLAGS=-DSWDEBUG && make clean && make
  # check that we can run the 'default' example
  - cd testing.sagebrush.master/Stepwat_Inputs && ./stepwat -f files.in -s -o -i
  # remove created files including (possibly) large output
  - make cleanall
